Repository xitu/tensorflow-docs, pull requests merged in 2018-03, with the labels that each got.

#21 translate tutorials/wide_and_deep.md
  tutorials/wide_and_deep.md
Labels: 正在校对

#34 在 iOS 中构建 TensorFlow & TensorFlow Lite 演示 (iOS)
  mobile/ios_build.md
  mobile/tflite/demo_ios.md
Labels: 正在校对

#33 集成 TensorFlow 库
  mobile/linking_libs.md
Labels: 翻译完成

#32 TensorFlow Mobile 简介
  mobile/mobile_intro.md
Labels: 正在校对

#20 translated tutorials/wide.md
  tutorials/wide.md
Labels: 正在校对

#22 低级 API 编程介绍
  programmers_guide/low_level_intro.md
Labels: 正在校对

#42 对涂鸦进行分类的循环神经网络
  tutorials/recurrent_quickdraw.md
Labels: 校对认领
