Repository xitu/tensorflow-docs, pull requests merged in 2018-04, with the labels that each got.

#44 TensorFlow Lite 简介
  mobile/tflite/index.md
Labels: 正在校对

#49 Update datasets_quickstart.md
  get_started/datasets_quickstart.md
Labels: 校对认领, 正在校对

#54 数据集性能
  performance/datasets_performance.md
Labels: 正在校对

#46 premade_estimators.md
  get_started/premade_estimators.md
Labels: 正在校对

#55 机器学习新手入门
  get_started/get_started_for_beginners.md
Labels: 正在校对

#48 Update feature_columns.md
  get_started/feature_columns.md
Labels: 正在校对

#53 创建定制化 Estimator
  get_started/custom_estimators.md
Labels: 翻译完成

#56 高性能模型
  performance/performance_models.md
Labels: 正在校对

#65 /deploy/s3.md and /mobile/tflite/demo_android.md
  deploy/s3.md
  mobile/tflite/demo_android.md
Labels: 校对认领, 正在校对
