Repository xitu/tensorflow-docs, pull requests merged in 2018-10, with the labels that each got.

#100 performance/xla/jit.md 翻译
  performance/xla/jit.md
Labels: 翻译完成

#99 api_docs/index.md文档翻译
  api_docs/index.md
Labels: DONE, 正在校对

#103 tutorials/keras/index.md 翻译
  tutorials/keras/index.md
Labels: DONE, 正在校对

#97 finish gpu.md translation
  install/gpu.md
Labels: DONE, 正在校对

#101 Translation/guide/keras.md
  guide/keras.md
Labels: DONE, 正在校对

#98 finish basic_text_classification translation
  tutorials/keras/basic_text_classification.ipynb
  tutorials/keras/basic_text_classification.md
Labels: help wanted, 校对认领, 正在校对
