Repository xitu/tensorflow-docs, pull requests merged in 2018-12, with the labels that each got.

#107 install/docker.md install/install_linux.md install/install_raspbian.md
  install/docker.md
  install/install_linux.md
  install/install_raspbian.md
Labels: DONE, 正在校对

#123 翻译tutorials/eager/index.md和tutorials/eager/custom_layers.ipynb
  tutorials/eager/custom_layers.ipynb
  tutorials/eager/index.md
Labels: 翻译完成

#127 模型优化
  performance/model_optimization.md
Labels: DONE, 正在校对

#128 翻译 tutorials/eager/custom_training.ipynb
  tutorials/eager/custom_training.ipynb
Labels: DONE, 正在校对

#133 翻译完成tfx/README.md, tutorials/_index.ipynb, Translation/tutorials/eager/automatic differentiation
  tfx/README.md
  tutorials/_index.ipynb
  tutorials/eager/automatic_differentiation.ipynb
Labels: DONE, 正在校对

#136 翻译完成tutorials/_index.yaml、tutorials/_toc.yaml
  tutorials/_index.yaml
  tutorials/_toc.yaml
Labels: DONE, 正在校对

#121 翻译 install/errors.md , install/lang_java.md
  install/errors.md
  install/lang_java.md
Labels: DONE, 正在校对

#125 20181201 翻译完成 install/install_sources.md, install/lang_c.md, install/lang_go.md, mobile/tflite/demo_android.md and mobile/tflite/performance.md
  install/install_sources.md
  install/lang_c.md
  install/lang_go.md
  mobile/tflite/demo_android.md
  mobile/tflite/performance.md
Labels: DONE, 正在校对

#138 Translated Linear model
  tutorials/estimators/linear.ipynb
  tutorials/estimators/linear.md
  tutorials/keras/basic_classification.ipynb
  tutorials/keras/basic_classification.md
Labels: DONE, 正在校对

#134 翻译完成 community/roadmap.md, community/style_guide.md, deploy/s3.md, install/_index.yaml, install/pip.html and install/source_windows.md
  community/roadmap.md
  community/style_guide.md
  deploy/s3.md
  install/_index.yaml
  install/pip.html
  install/source_windows.md
Labels: enhancement, 正在校对
