Repository xitu/tensorflow-docs, pull requests merged in 2018-05, with the labels that each got.

#66 /extend/new_data_formats.md
  extend/new_data_formats.md
Labels: 正在校对

#74 translation tensorflow-community-benchmarks.md contributing.md index.md groups.md security.md
  community/benchmarks.md
  community/contributing.md
  community/groups.md
  community/index.md
  community/security.md
Labels: 校对认领, 正在校对

#75 About page translation
  about/attribution.md
  about/bib.md
  about/index.md
  about/uses.md
Labels: 正在校对

#77 /community/documentation.md
  community/documentation.md
Labels: 校对认领, 正在校对

#76 /community/lists.md + roadmap.md + style_guide.md + swift.md
  community/lists.md
  community/roadmap.md
  community/style_guide.md
  community/swift.md
Labels: 正在校对

#71 完成「prepare model」的翻译
  mobile/prepare_models.md
Labels: 正在校对

#78 定点量化技术
  performance/quantization.md
Labels: 校对认领
